# Generated by Django 3.2.5 on 2022-05-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_question_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='msg_room',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
