# Generated by Django 3.2.5 on 2022-05-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_msg_msg_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='msg_study',
            field=models.CharField(blank=True, choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='msg',
            name='msg_type',
            field=models.CharField(blank=True, choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], max_length=200, null=True),
        ),
    ]
