# Generated by Django 3.2.5 on 2022-05-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220511_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='msg_room',
            field=models.CharField(blank=True, choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], max_length=200, null=True),
        ),
    ]
