# Generated by Django 3.2.5 on 2022-05-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_msg_msg_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='msg_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
