# Generated by Django 3.2.5 on 2022-05-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_msg_msg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='msg_room',
            field=models.CharField(blank=True, choices=[('labor', 'labor'), ('u1', 'u1'), ('u2', 'u2'), ('u3', 'u3'), ('u4', 'u4')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='msg',
            name='msg_study',
            field=models.CharField(blank=True, choices=[('nako', 'NAKO'), ('resist', 'RESIST'), ('red', 'RED')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='msg',
            name='msg_type',
            field=models.CharField(blank=True, choices=[('blut', 'Blut'), ('stuhl', 'Stuhl'), ('urin', 'Urin')], max_length=200, null=True),
        ),
    ]
