# Generated by Django 3.2.5 on 2022-05-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_msg_msg_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='msg_type',
            new_name='msg_blood',
        ),
        migrations.AddField(
            model_name='msg',
            name='msg_stool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='msg',
            name='msg_urin',
            field=models.BooleanField(default=False),
        ),
    ]
