# Generated by Django 3.2.5 on 2022-05-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20220518_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='msg_mark',
            field=models.BooleanField(default=False),
        ),
    ]
