# Generated by Django 3.2.5 on 2022-05-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_msg_msg_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='msg_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
